### PR TITLE
Remove BUMP MPI calls

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
See https://github.com/JCSDA/saber/pull/28#issuecomment-535855089 for details.

I have reproduced what is done for the "fckit_mpi_maxloc" function.

### CODE REVIEW

**Comment by mmiesch** [comment]
Just a comment that the Travis tests are failing just because this is not using the jcsda fork of eckit.  So, I believe this is ok to merge.  If we wish, we could in the future modify the .travis.yml file to use the jcsda fork of eckit for testing but then we'd have to make sure that's easily maintainable while still supporting a connection with upstream.

**Comment by travissluka** [comment]
@mmiesch @ytremolet I'm assuming that with this PR just merged, everyone who is not using a container now needs to point to the JCSDA eckit:develop branch inside their bundle? some of us have been bashing our heads on our keyboard for the past hour trying to figure out why suddenly nothing is working.

**Comment by christopherwharrop-noaa** [comment]
@travissluka - Yes, it just completely broke my builds.  Spent about 30 minutes hunting around trying to figure out why.  I had thought the authoritative eckit was the ecmwf version 1.1.0.

**Comment by mmiesch** [comment]
Apologies to both - we should have announced that.  I'll do so now on the GitHub team page.  Yes, to use the latest fckit, one must use the jcsda fork of eckit, tag 1.4.0.jcsda1 (or develop is sufficient).

**Pull request merged**
