### PR TITLE
Add missing allocation

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
OK, it was my fault again... I owe you a beer on my next trip to Boulder.
I think we can merge this fix quickly in `release-stable` to rerun all the CI tests with Intel19.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
I noticed that ECMWF `develop` already implemented a bugfix for `set_array_string`, so I replaced my bugfix with their one. Thus, no need for an upstream PR.

**Comment by mmiesch** [comment]
Thanks @benjaminmenetrier for addressing this but I'm getting this error with the latest tagged versions of eckit and atlas - what versions of eckit and atlas are you using?

```
[ 38%] Building Fortran object atlas/src/atlas_f/CMakeFiles/atlas_f.dir/internals/atlas_write_to_fortran_unit.F90.o
/Users/miesch/JEDI/code/working_copy/src/fv3-bundle/atlas/src/atlas_f/internals/atlas_write_to_fortran_unit.F90:11:36:

   11 |   use fckit_c_interop_module, only : copy_c_ptr_to_string
      |                                    1
Error: Symbol 'copy_c_ptr_to_string' referenced at (1) not found in module 'fckit_c_interop_module'
make[2]: *** [atlas/src/atlas_f/CMakeFiles/atlas_f.dir/internals/atlas_write_to_fortran_unit.F90.o] Error 1
make[1]: *** [atlas/src/atlas_f/CMakeFiles/atlas_f.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by benjaminmenetrier** [comment]
Hi @mmiesch, I still use `release-stable` for eckit and atlas. The goal here is to make all tests pass with the current `release-stable`. If it succeeds, it shouldn't be too hard to propagate the bugfix in `feature/release-staged`.

**Comment by benjaminmenetrier** [comment]
A new day, a new try... I used the optional valgrind-based tests of SABER and found other memory errors in `fckit_configuration`. Can you rerun the tests?

**Comment by wdeconinck** [comment]
> 
> 
> Thanks @benjaminmenetrier for addressing this but I'm getting this error with the latest tagged versions of eckit and atlas - what versions of eckit and atlas are you using?
> 
> ```
> [ 38%] Building Fortran object atlas/src/atlas_f/CMakeFiles/atlas_f.dir/internals/atlas_write_to_fortran_unit.F90.o
> /Users/miesch/JEDI/code/working_copy/src/fv3-bundle/atlas/src/atlas_f/internals/atlas_write_to_fortran_unit.F90:11:36:
> 
>    11 |   use fckit_c_interop_module, only : copy_c_ptr_to_string
>       |                                    1
> Error: Symbol 'copy_c_ptr_to_string' referenced at (1) not found in module 'fckit_c_interop_module'
> make[2]: *** [atlas/src/atlas_f/CMakeFiles/atlas_f.dir/internals/atlas_write_to_fortran_unit.F90.o] Error 1
> make[1]: *** [atlas/src/atlas_f/CMakeFiles/atlas_f.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

This was unintended. I did not mean for atlas to require a new version of fckit. I double-checked, and this particular subroutine is in fact no longer used. I have completely removed it upstream with commit: https://github.com/ecmwf/atlas/commit/8d933a3d5670572d17f245e93b168bf9b8e1850e

**Comment by mmiesch** [comment]
> 
> This was unintended. I did not mean for atlas to require a new version of fckit. I double-checked, and this particular subroutine is in fact no longer used. I have completely removed it upstream with commit: [ecmwf/atlas@8d933a3](https://github.com/ecmwf/atlas/commit/8d933a3d5670572d17f245e93b168bf9b8e1850e)

@wdeconinck - the problem was that the version of fckit I was using was *too new*.  This PR is designed to be merged into our existing `release-stable` branch of fckit.  We have a `feature/release-staged` version of fckit that is more up to date with ecmwf upstream and that we plan to merge this week, after we sort out a few remaining test failures in the new intel container.  So, no worries - we will not be using this routine moving forward.

**Pull request merged**
